### ISSUE TITLE
Add user authentication support?

### ISSUE THREAD

**Issue by 0400H** [cs01/pyxtermjs#23]
If not have authentication, it will make a great security risk.

**Comment by kaelianbaudelet** [comment]
Hi, **0400H**

Indeed it could be interesting that PyxtermJS has an authentication page, I rather agree.

Since Pyxtermjs does not guarantee a long term support, I decided to update Pyxtermjs by making a fork named **[Termsteel](https://github.com/afi-dev/Termsteel)** with a more beautiful web interface with customisation and a secure authentication system. 

https://user-images.githubusercontent.com/44731817/174507777-369c2dc8-8423-4316-9db5-dde028bba88d.mp4


I hope this will help you while waiting for a future update of Pyxtermjs.
